import Head from "next/head";
import Link from "next/link";
import Layout from "../components/layout";

import { SITE_NAME } from "../lib/constants";

function AIPolicy() {
  return (
    <Layout>
      <Head>
        <title>{`AI Policy | ${SITE_NAME}`}</title>
      </Head>
      <div className="grid md:grid-cols-3 mt-8 md:mt-16 pt-4 md:pt-8">
        <div className="md:col-span-2 md:col-start-2 max-w-md">
          <h1>AI policy</h1>
          <p>
            All content on this website is written by myself. I do not use AI
            (such as ChatGPT or other LLMs) to generate articles from prompts or
            similar. All content reflects my own thinking, ideas, style, and
            craft.
          </p>
          <p>
            Occasionally, I ask AI (such as ChatGPT or other LLMs) to summarize
            or re-state my own ideas on the basis of a complete skeleton I’ve
            written. Based on the response, I may reorder, restructure, or alter
            my original thinking. I personally write each draft and final copy.
          </p>
          <p>
            I used AI (specifically Dall•E 2) to generate illustrations for the
            article “
            <Link href="/writing/how-i-stopped-worrying-and-learned-to-love-the-ai">
              How I stopped worrying and learned to love the AI
            </Link>
            .” At this point I’m not sure I do love the AI for this purpose and
            I haven’t, nor do I plan to use it to generate imagery in the
            future. Instead, I typically use my own photos or imagery or photos
            or imagery taken from{" "}
            <a href="https://unsplash.com" target="_blank">
              Unsplash
            </a>{" "}
            or similar. It’s possible this may inadvertently be generated by AI
            without my knowing, in which case I’ll replace it if I learn as
            such.
          </p>
        </div>
      </div>
    </Layout>
  );
}

export default AIPolicy;
